name: .NET 5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[w/out CI]')"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: |
        dotnet publish ./Montage.RebirthForYou.Tools.CLI/Montage.RebirthForYou.Tools.CLI.csproj -c Release -o publish-r4utools -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=false --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true --version-suffix 'rc${{ github.run_number }}'
        dotnet publish ./Montage.RebirthForYou.Tools.GUI/Montage.RebirthForYou.Tools.GUI.csproj -c Release -o publish-deckbuilder4u -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=false --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true --version-suffix 'rc${{ github.run_number }}'
    - name: Upload Artifact (r4utools)
      uses: actions/upload-artifact@v2
      with:
        name: r4utools
        if-no-files-found: warn
        path: |
          publish-r4utools/*.dll
          publish-r4utools/*.exe
    - name: Upload Artifact (deckbuilder4u)
      uses: actions/upload-artifact@v2
      with:
        name: deckbuilder4u
        if-no-files-found: warn
        path: |
          publish-deckbuilder4u/*.dll
          publish-deckbuilder4u/*.exe