name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: |
        dotnet publish ./Montage.RebirthForYou.Tools.CLI/Montage.RebirthForYou.Tools.CLI.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --version-suffix 'rc${{ github.run_number }}'
        dotnet publish ./Montage.RebirthForYou.Tools.GUI/Montage.RebirthForYou.Tools.GUI.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true --version-suffix 'rc${{ github.run_number }}'
    - name: Upload Artifact (r4utools)
      uses: actions/upload-artifact@v2
      with:
        name: r4utools
        if-no-files-found: warn
        path: |
          Montage.RebirthForYou.Tools.CLI/bin/Release/netcoreapp3.1/win-x64/publish/*.dll
          Montage.RebirthForYou.Tools.CLI/bin/Release/netcoreapp3.1/win-x64/publish/*.exe
    - name: Upload Artifact (deckbuilder4u)
      uses: actions/upload-artifact@v2
      with:
        name: deckbuilder4u
        if-no-files-found: warn
        path: |
          Montage.RebirthForYou.Tools.GUI/bin/Release/netcoreapp3.1/win-x64/publish/*.dll
          Montage.RebirthForYou.Tools.GUI/bin/Release/netcoreapp3.1/win-x64/publish/*.exe