name: Release Cadence

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      shell: powershell
      run: |
        dotnet publish ./Montage.RebirthForYou.Tools.GUI/Montage.RebirthForYou.Tools.GUI.csproj -c Release -o publish -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=false --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish ./Montage.RebirthForYou.Tools.GUI/Montage.RebirthForYou.Tools.GUI.csproj -c Release -o publish -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=false --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish ./Montage.RebirthForYou.Tools.CLI/Montage.RebirthForYou.Tools.CLI.csproj -c Release -o publish -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=false --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true
        dotnet publish ./Montage.RebirthForYou.Tools.CLI/Montage.RebirthForYou.Tools.CLI.csproj -c Release -o publish -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=false --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true
        cd ./publish/
        Compress-Archive -DestinationPath ../r4utools-win-x64.zip -Path ./r4utools.exe
        Compress-Archive -DestinationPath ../r4utools-linux-x64.zip -Path ./r4utools
        Compress-Archive -DestinationPath ../deckbuilder4u-win-x64.zip -Path ./deckbuilder4u.exe
        Compress-Archive -DestinationPath ../deckbuilder4u-linux-x64.zip -Path ./deckbuilder4u
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Sample Release (TODO: Change this.)
          - First Change
          - Second Change
        draft: true
        prerelease: true
    - name: Add Release Artifact (r4utools / win-x64)
      id: upload-release-asset-1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./r4utools-win-x64.zip
        asset_name: r4utools-win-x64.zip
        asset_content_type: application/zip
    - name: Add Release Artifact (r4utools / linux-x64)
      id: upload-release-asset-2 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./r4utools-linux-x64.zip
        asset_name: r4utools-linux-x64.zip
        asset_content_type: application/zip
    - name: Add Release Artifact (deckbuilder4u / win-x64)
      id: upload-release-asset-3
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deckbuilder4u-win-x64.zip
        asset_name: deckbuilder4u-win-x64.zip
        asset_content_type: application/zip
    - name: Add Release Artifact (deckbuilder4u / linux-x64)
      id: upload-release-asset-4
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deckbuilder4u-linux-x64.zip
        asset_name: deckbuilder4u-linux-x64.zip
        asset_content_type: application/zip